### ISSUE TITLE
Docker file fails to load on Mac OS X; problem with workspace?

### ISSUE THREAD

**Issue by toqduj** [DiamondLightSource/adcorr#114]
Hey, 

I couldn't get the docker image to start (though this is my first foray into containers). From what I understand of the logs, the problem is with this line in the configuration. Is that something DLS-specific? 

	"workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,Z",
	"workspaceFolder": "/workspace",

**Comment by garryod** [comment]
Hi Brain,

I've managed to re-produce the issue on our iMac. The `Z` tag at the end of the `workspaceMount` is specific to Security Enhanced Linux (SELinux) where it reserves a volume for a single container. I have created a pull request #117 with an updated `devcontainer.json` which should work for you. Please let me know if this resolves the issue
