### ISSUE TITLE
Masking: replace masked values with NaN instead of zeros (or allow as option)

### ISSUE THREAD

**Issue by toqduj** [DiamondLightSource/adcorr#116]
Zero still has meaning (zero intensity is also information, and not uncommon in lab instruments), and will incorrectly affect any further operations such as calculations of means, binning, etc.. Replacing masked values with NaNs will ensure that any further attempts at computation using these pixels will be clearly invalid.

**Comment by garryod** [comment]
Hi Brian,

The `mask_frames` function returns a `numpy.ma.MaskedArray` which persists all underlying data whilst restricting operations to the un-masked values, a dense array with filled values can be retrieved by calling `my_array.filled(some_value)`. It may be the case that your visualisation library is filling these values with zero in the background.

**Comment by toqduj** [comment]
Ah ok, I guess I got confused with the wording of the masking.py method comment, which says:
 """Replaces masked elemenets of frames in a stack with zero.

Now I understand with masked elements, you mean the elements in the mask.

**Comment by garryod** [comment]
Ah, I should've looked at the docstring, the wording within it is plainly wrong and has been carried over from the first pass implementation which did indeed replace masked regions with zero. I'll merge a change with new wording which correctly describes the functionality.
