### ISSUE TITLE
Units support

### ISSUE THREAD

**Issue by toqduj** [DiamondLightSource/adcorr#119]
One of the conclusions from the data analysis round robin was that users make mistakes converting between units themselves. Units support and conversion should be offered by the corrections class. 

I know Tim's got plans for this, but I just wanted to mention it so it is not forgotten.

**Comment by garryod** [comment]
This is a good point, I will get in touch with @timsnow on this topic. It seems to me that there are two ways to go with regard to supporting units / unit conversions:

1. Ship a series of functions which convert various units to the internal representation (SI) and a series which revert back to whatever the user desires - likely using [`scipy.constants`](https://docs.scipy.org/doc/scipy/reference/constants.html)
2. Make the library unit aware using a library which attaches unit metadata to values (e.g. [`pint`](https://pint.readthedocs.io/en/stable/))

It's possible that the latter of these is already possible though I have not yet tested it. It may be sufficient to add this to the example usage & testing suite.

**Comment by toqduj** [comment]
I've found for McSAS that it's useful to have three unit definitions: read-in units, internal units, and display/output units. For this, I've used a python wrapper for udunits in the past (based on its use in SasView). Best wait for @timsnow as the packages he's considering might already have this support built-in.

**Comment by garryod** [comment]
I have just spoken with @timsnow, we have decided to remain on the `numpy` track for now, as such it is worth exploring the available options within this ecosystem. Ideally, we would like to implement units with minimal complexity increase and without using any additional dependencies if possible. I will have a play with  [`pint`](https://pint.readthedocs.io/en/stable/) as soon as I have the time and see if units are propagated correctly.

**Comment by toqduj** [comment]
Ok makes sense. 
Did a very quick test and seems to do what it says on the tin:
![image](https://user-images.githubusercontent.com/5449929/195548226-9715a424-1ee7-4e18-adeb-ae7204df5db2.png)
