### ISSUE TITLE
azimuthal/radial/box Averager missing

### ISSUE THREAD

**Issue by toqduj** [DiamondLightSource/adcorr#120]
While an external averager like PyFAI can be recommended, a basic reference implementation would not be amiss for testing and checking. I can provide one if necessary, but they're not too hard to write either, as long as one eschews the nonsense of pixel splitting ;). 

An averager determines between each set of (log- or lin-spaced) bin boundaries:
 - mean value for I, the dependent variable
 - standard error on the mean🍺 for the above
 - propagated uncertainty estimates for the above
 - mean value for Q, Phi, Qx, Qy, two theta or whatever is used for the independent variable(s)
 - standard error on the mean for those too
 - propagated uncertainty estimates for the above. 
 - mean value for the scaling factors
 - standard error on the mean🍺 for the above
 - propagated uncertainty estimates for the above

So the averaging step actually produces quite a few "uncertainties", which can then be mixed-and-matched however people see fit. I usually take the largest uncertainty estimator as the one to feed the user, but the remainder can be stored for traceability. 
Creating a single uncertainty estimator from multiple feed values could be a good separate processing step. 

Additionally (ok, so this isn't as straightforward as I initially envisioned), I use this binning to merge data from multiple detectors and configurations. When I do that, I weigh their contributions by the datapoint uncertainty: datapoints with a small relative uncertainty weigh more to the average than datapoints with a higher uncertainty. Details: https://lookingatnothing.com/index.php/archives/2650 
This weighting should probably be left optional.

**Comment by garryod** [comment]
Whilst it would be nice to have a set of reference reduction / reconstruction sets it may be outwith the scope of this project, as we aim to transform raw detector data into a corrected frame and nothing more. I haven't yet tested how `PyFAI` works with `numcertain`, if this is unsuccessful we can look at up-streaming a issue to one of these or in the worst case, develop a separate library which works with uncertainities.
